language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run docs:build

after_script:
  - cd docs/.vuepress/dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add -A
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/liuyib/hexo-theme-stun.git
